SOURCE = server.c util/serverfunctions.c util/servernetworking.c
HEADER = util/serverfunctions.h util/servernetworking.h
OUT = startserver
CC = gcc
FLAGS = -Wall

all:
	$(CC) $(FLAGS) -o $(OUT) $(SOURCE) $(HEADER)